### ISSUE TITLE
Gnome 3.14 : Installation problem with workspace-grid-for-3.16.zip, BUT works well from git

### ISSUE THREAD

**Issue by brunetton** [zakkak/workspace-grid-gnome-shell-extension#10]
Hi. Fist of all, I wanted to say that this extension is absolutely became my life saver. I use it all days, all day long; so thanks very much !

Last week, I upgrated from Debian Wheezy to Jessie, and some gnome shell extensions didn't worked anymore. Workspace-grid was one of them.

## Installation from workspace-grid-for-3.16.zip (doesn't works)

Manual installation of `workspace-grid-for-3.16.zip` file (from 22b96b2 - v1.3.4) makes `gnome-tweak-tool` internal error. Console logs :

<pre>
WARNING : Error parsing theme zip
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gtweak/tweaks/tweak_group_shell_extensions.py", line 251, in _on_file_set
    verb = _("%s extension updated successfully") % extension_uuid
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8: ordinal not in range(128)
</pre>

But `~/.local/share/gnome-shell/extensions/workspace-grid@mathematical.coffee.gmail.com/` exists. When I reload gnome-shell (`gnome-shell --replace`), I have an error in console :

<pre>
Gjs-Message: JS LOG: Extension "workspace-grid@mathematical.coffee.gmail.com" had error: TypeError: Shell.ActionMode is undefined
</pre>

## Installation from Git (works)

This way of install works perfectly for me :

<pre>
cd ~/.local/share/gnome-shell/extensions
git clone https://github.com/zakkak/workspace-grid-gnome-shell-extension.git
cd workspace-grid-gnome-shell-extension/
git co 3.14
make   # generate needed `workspace-grid@mathematical.coffee.gmail.com/schemas/gschemas.compiled` file
mv workspace-grid@mathematical.coffee.gmail.com/ ..
cd ..
rm -rf workspace-grid-gnome-shell-extension
# Finaly reload gnome-shell
gnome-shell --replace
</pre>

I don't know if this is really a bug, but at least this could be usefull to another user.

----
Debian Jessie - Gnome 3.14

**Comment by zakkak** [comment]
Since you are running Gnome 3.14 you should use [workspace-grid-for-3.12-and-3.14.zip](https://github.com/zakkak/workspace-grid-gnome-shell-extension/releases/download/v1.3.2/workspace-grid-for-3.12-to-3.14.zip), note however that it does not include the latest changes ( see #2 ) from branch 3.14.

[workspace-grid-for-3.16.zip](https://github.com/zakkak/workspace-grid-gnome-shell-extension/releases/download/v1.3.4/workspace-grid-for-3.16.zip) is meant to work only with Gnome 3.16, but it seems that I mistakenly added the message *Release v1.3.4 for 3.12 to 3.16* instead of *Release v1.3.4 for 3.16*.

**Comment by brunetton** [comment]
Sorry, I messed up : this was not with workspace-grid-for-3.16.zip but workspace-grid-for-3.12-to-3.16.zip file => I updated the bug description.

I still have the same bug when installing from workspace-grid-for-3.12-to-3.14.zip with gnome-teak-tool (I suppose it's a Debian bug) **BUT** it works well then.

Thanks :)

**Comment by zakkak** [comment]
Hmmm I am not sure why this happens I am also using gnome tweak tool and did not have similar problems.

From the message I understand that the uuid contains a non ASCII character, however inspecting the file It seems OK to me.

```
$ file metadata.json 
metadata.json: ASCII text, with very long lines
```

I also checked with hexdump and 0xc3 does not appear in the uuid.

**Comment by terzag** [comment]
I can confirm the same issue with Ubuntu 15.04 (Gnome 3.14). When trying to install it from Gnome Tweak Tool, I get a message "invalid extension" in the notifications area. In the terminal, I get the same message as brunetton.

**Comment by paulochf** [comment]
same as @terzag , but on Gnome 3.10

**Comment by zakkak** [comment]
@paulochf which archive did you use?  I think I never created an archive for 3.10

**Comment by paulochf** [comment]
I changed the branch to 3.10 and clicked Download button on the right.

It gave a file named "3.10.zip", which I though it was from 3.10 branch. Did I get it wrong?

**Comment by zakkak** [comment]
This way, it will not work.  With that procedure you essentially create a zip archive of the whole repository.

To create a proper archive for `gnome-tweak-tool` you need to:
1. clone the repository
2. checkout 3.10 branch
3. run `make zip`

**Comment by paulochf** [comment]
@zakkak: thanks, but it's working already. =)

**Comment by yadutaf** [comment]
This 0xc3 char is in the translations, not in the extensions. If you manually "tweak" the installer to bypass the i18n on this specific line, installation is fine too.

**Comment by zakkak** [comment]
Any idea how we could fix it on our side?

**Comment by yadutaf** [comment]
Installing from https://extensions.gnome.org/extension works as expected + mush easier to find :)

**Comment by yadutaf** [comment]
Hmm, that was an illusion. The extension as tested was installed, just not activated.

**Comment by zakkak** [comment]
@yadutaf The https://extensions.gnome.org/extension/484/workspace-grid/ version is not working with 3.12, 3.14 and 3.16.  I do not understand what you mean with "Tested with https://extensions.gnome.org/extension/120/system-monitor/ which is not installed by default"

**Comment by yadutaf** [comment]
If it were up to date, it would work (provided proper gnome integration plugin is installed). Like the system-monitor does. It must be triggering a different code path.
