### ISSUE TITLE
Gnome 3.16 - Keyboard shortcut for dragging window to other workspace is not working

### ISSUE THREAD

**Issue by EliasJorgensen** [zakkak/workspace-grid-gnome-shell-extension#12]
I'm coming from Gnome 3.14 on Ubuntu Gnome, where i used ctrl+shift+alt to drag a window to another workspace. However, recently i switched to Manjaro Linux which uses 3.16.
I installed the 3.16 version of workspace grid, and i can switch workspaces perfectly fine with ctrl+alt+arrow key, but when i hold down shift along with the rest of them it makes no difference.

**Comment by zakkak** [comment]
Does it work when you disable the workspace-grid extension?

Is the shortcut properly set?
If yes, did you try with a different shortcut?

Does it work when moving the window one workspace up or down instead of
right or left?

**Comment by EliasJorgensen** [comment]
It didn't work when i disabled the extension.
Also, the shortcuts were properly set but they wouldn't work..
So i tried setting the same shortcuts again and that did the trick.

I guess the shortcuts weren't properly saved or something.
