### ISSUE TITLE
Gnome 3.16 - "children[i] is undefined" if dynamic Workspace Creation

### ISSUE THREAD

**Issue by brunetton** [zakkak/workspace-grid-gnome-shell-extension#13]
When dynamic Workspace Creation is enabled (gnome-tweak-tool > Workspaces > Workspace Creation), we see only one line of desktops instead of a grid, and each time switching workspace :

    sept. 07 18:47:29 Loulou gnome-session[1449]: (gnome-shell:2020): Gjs-WARNING **: JS ERROR: TypeError: children[i] is undefined
    sept. 07 18:47:29 Loulou gnome-session[1449]: WorkspaceSwitcherPopup<._allocate@/home/bruno/.local/share/gnome-shell/extensions/workspace-grid@mathematical.coffee.gmail.com/extension.js:394
    sept. 07 18:47:29 Loulou gnome-session[1449]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
    sept. 07 18:47:29 Loulou gnome-session[1449]: LayoutManager<._init/<@resource:///org/gnome/shell/ui/layout.js:204

Debian testing
Gnome 3.16.2

**Comment by brunetton** [comment]
Solution : change setting from *dynamic* to *static*.

This should maybe be added to README, isn't it ?

**Comment by zakkak** [comment]
Yes, I will be happy to merge a pull request fixing it.
