### ISSUE TITLE
Grid changes size unpredictably (3.14)

### ISSUE THREAD

**Issue by fowlslegs** [zakkak/workspace-grid-gnome-shell-extension#19]
As I move about my desktop grid the size of the grid display overlay changes. The size of the grid should be static.

GNOME 3.14 on Debian stable.

**Comment by zakkak** [comment]
Please enable the *User themes* extension to fix this.

*Workspace grid* currently overirdes the css decoration to fix such behaviors.

**Comment by fowlslegs** [comment]
A custom theme can apparently also cause this problem. See https://github.com/zakkak/workspace-grid-gnome-shell-extension/issues/20#issuecomment-163592584.
