### ISSUE TITLE
Workspace grid makes the desktop environment in GNOME Classic crash

### ISSUE THREAD

**Issue by ingnil** [zakkak/workspace-grid-gnome-shell-extension#24]
Yesterday I installed the latest CentOS 7 on a VirtualBox VM, and since I was missing my old workspace grid from GNOME 2 I quickly searched and found your GNOME Shell extension. It installed fine and worked fine until I left the computer for a while. When I tried to wake it up from the locked screen, the desktop environment crashed. I was thrown out to the login screen, but every time I tried to login, the desktop environment crashed.

I managed to restore the system by entering GNOME 3 mode (CentOS 7 uses GNOME Classic mode by default) and disabling the extension. After that I could logout and login again using the GNOME Classic mode.

Is there any way I can help? Are there any crash logs that I can send? I am a seasoned Linux user and software developer, but GNOME 3 is new to me, so don't expect me to find my way around on that part yet.

**Comment by zakkak** [comment]
A dump from `journalctl /usr/lib/gnome-session/gnome-session-binary` might be informative.
Other than that I am also not that familiar with GNOME development, I just maintain the extension.

**Comment by zakkak** [comment]
Bump
