### ISSUE TITLE
how to assign labels?

### ISSUE THREAD

**Issue by andreasio** [zakkak/workspace-grid-gnome-shell-extension#30]
Can't find instruction on how to assign labels to workspaces?

**Comment by zakkak** [comment]
Use `dconf-editor` and go to `/org/gnome/desktop/wm/preferences/workspace-names`, then change the value to whatever you wish.

e.g.
![screenshot from 2017-01-28 02-02-52](https://cloud.githubusercontent.com/assets/1435395/22392052/262a96de-e4fe-11e6-9dee-58377978693c.png)
