### ISSUE TITLE
Doesn't work with a strange behavior

### ISSUE THREAD

**Issue by freeroot** [zakkak/workspace-grid-gnome-shell-extension#32]
I don't know why this extension have this strange behavior on my laptop.

![grid bug](https://cloud.githubusercontent.com/assets/20989929/20644840/111d8762-b446-11e6-99fb-2b2691804b30.png)

I can answer any questions to find a solution but my knowledge of gnome extension is null for the moment^^.

**Comment by zakkak** [comment]
What are your settings?
Do you use static workspaces? 
Is the number of workspaces set properly, both in gnome and the extension?

**Comment by freeroot** [comment]
Gnome :
![image](https://cloud.githubusercontent.com/assets/20989929/22395953/f7c1345c-e54c-11e6-83ce-d91e587fd220.png)
This extension :
![image](https://cloud.githubusercontent.com/assets/20989929/22395956/23dfcb70-e54d-11e6-8bdb-884b0473b586.png)

**Comment by zakkak** [comment]
The workspaces should be set to static instead of dynamic. Please try changing this and see if it works.

**Comment by freeroot** [comment]
Ok, it works, thank you. It should be great to add it in comment in setting by a second note why not.

Thanks

**Comment by zakkak** [comment]
That's a good point, added with 59e2e9c0b0750960a670a105dd695c0fbb253b7c
