### ISSUE TITLE
Wrap workspace switching

### ISSUE THREAD

**Issue by RobotCaleb** [zakkak/workspace-grid-gnome-shell-extension#34]
It would be nice if there was an option to wrap around from bottom <-> top or left <-> right when switching workspaces.

**Comment by zakkak** [comment]
This is already available in the Workspace Grid settings menu.
![screenshot from 2017-01-28 01-29-42](https://cloud.githubusercontent.com/assets/1435395/22391381/88004354-e4f9-11e6-910c-c2d0968cbd0b.png)
