### ISSUE TITLE
Number of workspaces limited to two in gnome-shell 3.22.2

### ISSUE THREAD

**Issue by fvdnabee** [zakkak/workspace-grid-gnome-shell-extension#36]
I'm experiencing an issue where, regardless of the number of workspaces I set in the settings dialog, the number of workspaces is limited to two. The workspace switcher UI is sized correctly according to the number of columns and rows of the extension. However, I can only use the top left and top middle workspace. I'm running gnome shell 3.22.2 and extension version 1.3.9.

I made a screencast that demonstrates the issue and am happy to debug the issue further, only I don't have any experience with gnome shell extensions.
Screencast: https://vid.me/1odn

**Comment by spacemoose** [comment]
Have you tried using gnome-tweak-tool to disable dynamic workspace creation?  This solved the issue for me.

I would still call this a bug though.  I think the plugin should set this automatically when enabled, as well as adjust the number of workspaces.

**Comment by fvdnabee** [comment]
Disabling dynamic workspace creation fixed the issue for me as well, thanks @spacemoose !
Maybe installing the grid extension should disable dynamic workspace creation automatically?

**Comment by spacemoose** [comment]
I think that should be the case.  If not, it should at least be documented.

**Comment by zakkak** [comment]
This is a known issue (see #11).
PRs are welcome

**Comment by zakkak** [comment]
@spacemoose it is documented in the [readme](https://github.com/zakkak/workspace-grid-gnome-shell-extension#quirks). I added some headings to make it more visible.
