### ISSUE TITLE
Favorites and list of running applications is moved when extension is enabled

### ISSUE THREAD

**Issue by oleid** [zakkak/workspace-grid-gnome-shell-extension#6]
Using your version of the plugin I thought the bug was gone, but I was mistaken.
I think it's best explained when looking at screenshots.

![With extension](https://cloud.githubusercontent.com/assets/3369899/5229297/c202f9ba-7715-11e4-813c-d0eabfb59f69.png)
![Without extension](https://cloud.githubusercontent.com/assets/3369899/5229296/c1fea2de-7715-11e4-9093-28fabdcad791.png)

If you have a lot of windows opened or a lot of favourite apps, the icons on the very left (not the app overview!) disappear with the extensions enabled.

ArchLinux, GNOME 3.14 -- but I noticed it before with older Shell versions, too.

**Comment by kubatop** [comment]
I confirm the same issue on Debian Jessie with standard GNOME 3.14 from the distribution.

It occurs when many rows of workspaces are enabled.
For 3 rows nad 2 columns everything works fine. Even after setting 6 rows nad 2 columns (total of 12 worspaces) is everthing OK until gnome-shell is restarted.
![screenshot from 2015-08-11 17 28 45](https://cloud.githubusercontent.com/assets/13750958/9202052/391073da-4050-11e5-8a14-0ecef5ec13d0.png)

But after restart is all the content moved down.
![screenshot from 2015-08-11 17 28 57](https://cloud.githubusercontent.com/assets/13750958/9202081/5511d736-4050-11e5-9a52-469a14b782da.png)

Even if we go back to 3 rows and 2 columns of workspaces, all components are moved down until next gnome-shell restart.
![screenshot from 2015-08-11 17 29 13](https://cloud.githubusercontent.com/assets/13750958/9202097/74dddfe2-4050-11e5-95ed-3985ba4cfb7c.png)

**Comment by kubatop** [comment]
I just discovered relation with one more serious bug (originally I wanted to report it separately) which occurs when using this extension. When there are many rows of workspaces (such as after gnome-shell restart will occur issue previously discussed, e.g. 6), trying to lock screen ends with gnome-shell failure, which forces user to log out and gnome-shell is then restarted with all extensions disabled.

Logs are not very verbose, but I attach what I have found:

```
demon.log
x-session-manager[14887]: WARNING: Application 'gnome-shell.desktop' killed by signal 6

kern.log
x-session-manager[14887]: Unrecoverable failure in required component gnome-shell.desktop

messages, syslog, user.log (same messages)
gnome-session[14887]: **
gnome-session[14887]: mutter:ERROR:core/screen.c:1250:update_num_workspaces: assertion failed: (w->windows == NULL)
gnome-session[14887]: x-session-manager[14887]: WARNING: Application 'gnome-shell.desktop' killed by signal 6
gnome-session[14887]: (gnome-settings-daemon:14952): media-keys-plugin-WARNING **: Couldn't lock screen: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)
```

**Comment by mgorelkin** [comment]
Seeing the same effect; bumping this to see if there's a known fix for this yet? Perhaps a width variable used for a height somewhere?
