### ISSUE TITLE
try 3.16 in archlinux

### ISSUE THREAD

**Issue by c3h3** [zakkak/workspace-grid-gnome-shell-extension#9]
I tried the latest version in archlinux ... 

and get the errors ...

![screenshot from 2015-04-10 11-09-05](https://cloud.githubusercontent.com/assets/748256/7086575/3ddb0c98-df72-11e4-8889-fafdf3e30ef0.png)

![screenshot from 2015-04-10 11-08-58](https://cloud.githubusercontent.com/assets/748256/7086577/3fcfa838-df72-11e4-9019-b91406c30229.png)

**Comment by zakkak** [comment]
The error says that you are missing `schemas/gschemas.compiled`. Maybe something went wrong when installing the extension.  Did you try completely removing it and installing it again?

The zip file sha1sum should be 
```
6c46a3b2e8b8544ee14c68bb262179a41ba239dd  workspace-grid-for-3.12-to-3.16.zip
```

I am also on Arch and it works fine (except for some styling issues)

**Comment by c3h3** [comment]
thanks very much !

After re-install with workspace-grid-for-3.12-to-3.16.zip

all things works fine !!!

**Comment by zakkak** [comment]
Nice! (:
